-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 08:33:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fulanorodas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fulanorodas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fulanorodas2`;
USE `fulanorodas2` ;

-- -----------------------------------------------------
-- Table `fulanorodas`.`acabamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`acabamento` (
  `idacabamento` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acabamento` VARCHAR(100) NULL DEFAULT NULL,
  `idproduto` INT(11) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idacabamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`categorias` (
  `idcategorias` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `datalateracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `idfabricante` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`clientes` (
  `idclientes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `razao` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj_cpf` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(12) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `idmodelocarro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`cobranca` (
  `idcobranca` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idlicenca` INT(11) NULL DEFAULT NULL,
  `datavencimento` DATETIME NULL DEFAULT NULL,
  `datapgto` DATETIME NULL DEFAULT NULL,
  `idproduto` INT(11) NULL DEFAULT NULL,
  `pago` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idcobranca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`contatos` (
  `idcontatos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idclientes` INT(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `cnpjrevenda` VARCHAR(15) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `nomecontato` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcontatos`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`contratos` (
  `idcontratos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL DEFAULT NULL,
  `datainicial` DATETIME NULL DEFAULT NULL,
  `datafinal` DATETIME NULL DEFAULT NULL,
  `arquivocontrato` BLOB NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcontratos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`fabricantes` (
  `idfabricantes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `razao` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idfabricantes`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`licencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`licencas` (
  `idlicencas` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` INT(11) NOT NULL COMMENT '92228895415',
  `razao` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL COMMENT '09634-000',
  `telefone` VARCHAR(16) NOT NULL COMMENT '+55(11)942498529',
  `email` VARCHAR(100) NOT NULL,
  `idproduto` INT(11) NOT NULL,
  PRIMARY KEY (`idlicencas`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`linha` (
  `idlinha` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idfabricante` INT(11) NULL DEFAULT NULL,
  `linha` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `datacadastro` DATETIME NULL DEFAULT NULL,
  `datalterecao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `idcategoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idlinha`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`login` (
  `idlogin` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(1) NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `idcliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`logs` (
  `idlogs` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `arquivo` LONGBLOB NULL DEFAULT NULL,
  `datainclusao` DATETIME NULL DEFAULT NULL,
  `idrevenda` INT(11) NULL DEFAULT NULL,
  `nomearquivo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idlogs`))
ENGINE = InnoDB
AUTO_INCREMENT = 756
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`marca` (
  `idmarca` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `datainclusao` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `logo` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`menus` (
  `idmenus` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `captionmenu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmenus`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`modelos` (
  `idmodelos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idmarca` INT(11) NULL DEFAULT NULL,
  `datainclusao` DATETIME NULL DEFAULT NULL,
  `datalateracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `ano` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idmodelos`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`permissoes` (
  `idpermissoes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `idmenu` INT(11) NULL DEFAULT NULL,
  `permitido` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`idpermissoes`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`posicionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`posicionamento` (
  `idposicionamento` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idproduto` INT(11) NULL DEFAULT NULL,
  `idveiculo` INT(11) NULL DEFAULT NULL,
  `top` INT(11) NULL DEFAULT NULL,
  `left` INT(11) NULL DEFAULT NULL,
  `Align` VARCHAR(45) NULL DEFAULT 'alNone',
  `BevelOuter` VARCHAR(45) NULL DEFAULT 'bvNone',
  `BorderStyle` VARCHAR(45) NULL DEFAULT 'bsSingle',
  `Caption` VARCHAR(45) NULL DEFAULT '',
  `Color` VARCHAR(45) NULL DEFAULT 'clNone',
  `DockSite` VARCHAR(4) NULL DEFAULT 'True',
  `DoubleBuffered` VARCHAR(4) NULL DEFAULT 'true',
  `DragKind` VARCHAR(45) NULL DEFAULT 'dkDock',
  `DragMode` VARCHAR(45) NULL DEFAULT 'dmAutomatic',
  `Enabled` VARCHAR(4) NULL DEFAULT 'True',
  `Height` INT(11) NULL DEFAULT NULL,
  `Movable` VARCHAR(4) NULL DEFAULT 'True',
  `Name` VARCHAR(45) NULL DEFAULT 'JvPanel_',
  `Transparent` VARCHAR(4) NULL DEFAULT 'True',
  `Width` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idposicionamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`produtos` (
  `idprodutos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NULL DEFAULT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `preco` DECIMAL(12,2) NULL DEFAULT NULL,
  `aro` INT(11) NULL DEFAULT NULL,
  `idfabricante` INT(11) NULL DEFAULT NULL,
  `datainclusao` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  `lancamento` VARCHAR(1) NULL DEFAULT NULL,
  `furacao` INT(11) NULL DEFAULT NULL,
  `offset_et` INT(11) NULL DEFAULT NULL,
  `idlinha` INT(11) NULL DEFAULT NULL,
  `idacabamento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`usuarios` (
  `idusuarios` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `tipo` VARCHAR(1) NOT NULL DEFAULT 'U',
  `idcliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fulanorodas`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fulanorodas2`.`veiculos` (
  `idveiculos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL DEFAULT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `idmarca` INT(11) NULL DEFAULT NULL,
  `ano` INT(11) NULL DEFAULT NULL,
  `idmodelo` INT(11) NULL DEFAULT NULL,
  `datainclusao` DATETIME NULL DEFAULT NULL,
  `dataalteracao` DATETIME NULL DEFAULT NULL,
  `dataexclusao` DATETIME NULL DEFAULT NULL,
  `ativo` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idveiculos`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
