CREATE TABLE fred.chaves (
  id_chave INT(11) NOT NULL AUTO_INCREMENT,
  razao VARCHAR(200) DEFAULT NULL,
  cnpj VARCHAR(18) DEFAULT NULL,
  PRIMARY KEY (id_chave)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;