--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/05/2015 12:01:40
-- Server version: 5.6.23-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE fred;

--
-- Definition for table chaves
--
DROP TABLE IF EXISTS chaves;
CREATE TABLE chaves (
  id_chave INT(11) NOT NULL AUTO_INCREMENT,
  razao VARCHAR(200) DEFAULT NULL,
  cnpj VARCHAR(18) DEFAULT NULL,
  PRIMARY KEY (id_chave)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table registro
--
DROP TABLE IF EXISTS registro;
CREATE TABLE registro (
  id INT(11) NOT NULL AUTO_INCREMENT,
  id_chave INT(11) DEFAULT NULL,
  chave VARCHAR(200) DEFAULT NULL,
  data_inc DATE DEFAULT NULL,
  data_exp DATE DEFAULT NULL,
  contrasenha VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table chaves
--
INSERT INTO chaves VALUES
(1, 'conect video', '10.521.203/0001-87');

-- 
-- Dumping data for table registro
--
INSERT INTO registro VALUES
(1, 1, '87PV8S1WD-WX41A513424222/05/2015', '2015-05-22', '2015-06-21', '123'),
(2, 1, '87PV8S1WD-WX41A513424222/05/2015', '2015-05-22', '2015-06-21', '1234'),
(3, 1, '87PV8S1WD-WX41A513424221/05/2015', '2015-05-21', '2015-06-20', '12345'),
(4, 1, '87PV8S1WD-WX41A513424221/05/2015', '2015-05-21', '2015-06-20', '87PV8S1WD-WX41A513424221/05/2015I4ILG5MUY591NG1');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;