-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 09:14:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema conect2022
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conect2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conect2022` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `conect2022` ;

-- -----------------------------------------------------
-- Table `conect2022`.`cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conect2022`.`cobranca` (
  `idcobranca` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idlicenca` INT(11) NULL DEFAULT NULL,
  `datavencimento` DATETIME NULL DEFAULT NULL,
  `datapgto` DATETIME NULL DEFAULT NULL,
  `idproduto` INT(11) NULL DEFAULT NULL,
  `pago` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idcobranca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `conect2022`.`licencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conect2022`.`licencas` (
  `idlicencas` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` INT(11) NOT NULL COMMENT '92228895415',
  `razao` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL COMMENT '09634-000',
  `telefone` VARCHAR(16) NOT NULL COMMENT '+55(11)942498529',
  `email` VARCHAR(100) NOT NULL,
  `idproduto` INT(11) NOT NULL,
  PRIMARY KEY (`idlicencas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `conect2022`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conect2022`.`produtos` (
  `idprodutos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `datainicial` DATETIME NOT NULL,
  `datafinal` DATETIME NOT NULL,
  `linkhotmart` VARCHAR(200) NOT NULL,
  `linkvideoyoutube` VARCHAR(200) NULL DEFAULT NULL,
  `preco` DECIMAL(12,2) NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `LinkPagDoProduto` VARCHAR(200) NULL DEFAULT NULL,
  `qrcode` BLOB NULL DEFAULT NULL,
  `capa` BLOB NULL DEFAULT NULL,
  `fabricante` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
